server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #配置nacos地址,前面不能加http://

management:
  endpoints:
    web:
      exposure:
        include: "*"
