server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建动态路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route  #路由的id，没有固定规则，但要求唯一
          uri: lb://cloud-payment-service
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路由相匹配的进行路由

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**  #这个p一定要大写！！！！
            - After=2021-08-09T11:51:43.019+08:00[Asia/Shanghai]

        - id: payment_route3
          uri: https://news.baidu.com
          predicates:
            - Path=/finance  #这个p一定要大写！！！！

        - id: payment_route4
          uri: https://news.baidu.com
          predicates:
            - Path=/mil  #这个p一定要大写！！！！

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

